const express = require('express')
const router = express.Router()
const IndexController = require('./controllers/Index.controller')
const LoginController = require('./controllers/Login.controller')
const RegisterController = require('./controllers/Register.controller')
const MassiveController = require('./controllers/Massive.controller')
const verifyJWT = require('./middleware/jwtVerify')
const jwtVerify = require('./middleware/jwtVerify')

router.get('/', IndexController.index)
router.post('/login', LoginController.login)
router.post('/register', RegisterController.register)
router.get('/city', IndexController.city)
router.get('/colaborator', IndexController.colaborator)
router.post('/create', verifyJWT, IndexController.create)
router.post('/search', IndexController.search)
router.get('/teste', IndexController.teste)
router.post('/delete', IndexController.delete)
router.post('/createMassive', jwtVerify, MassiveController.createMassive)
router.get('/Massive', MassiveController.massive)
router.get('/cofee', MassiveController.massive)
router.get('/addCofee', MassiveController.massive)

router.get('/t', jwtVerify, (req, res) => {
    res.json(req.user)
})
module.exports = router 